# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


import error_code_pb2

DESCRIPTOR = descriptor.FileDescriptor(
  name='achieve.proto',
  package='',
  serialized_pb='\n\rachieve.proto\x1a\x10\x65rror_code.proto\"I\n\x0ep_achieve_info\x12\x11\n\tachieveID\x18\x01 \x02(\x05\x12\x12\n\x07\x63ontent\x18\x02 \x01(\x05:\x01\x30\x12\x10\n\x05state\x18\x03 \x01(\x05:\x01\x31\"\x12\n\x10\x63\x32s_achieve_list\"9\n\x10s2c_achieve_list\x12%\n\x0c\x61\x63hieve_list\x18\x01 \x03(\x0b\x32\x0f.p_achieve_info\"+\n\x16\x63\x32s_get_achieve_reward\x12\x11\n\tachieveID\x18\x01 \x02(\x05\"3\n\x16s2c_get_achieve_reward\x12\x19\n\x04\x63ode\x18\x01 \x01(\x0e\x32\x07.e_code:\x02ok\"6\n\x12s2c_update_achieve\x12 \n\x07\x61\x63hieve\x18\x01 \x03(\x0b\x32\x0f.p_achieve_info')




_P_ACHIEVE_INFO = descriptor.Descriptor(
  name='p_achieve_info',
  full_name='p_achieve_info',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='achieveID', full_name='p_achieve_info.achieveID', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='content', full_name='p_achieve_info.content', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='state', full_name='p_achieve_info.state', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=35,
  serialized_end=108,
)


_C2S_ACHIEVE_LIST = descriptor.Descriptor(
  name='c2s_achieve_list',
  full_name='c2s_achieve_list',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=110,
  serialized_end=128,
)


_S2C_ACHIEVE_LIST = descriptor.Descriptor(
  name='s2c_achieve_list',
  full_name='s2c_achieve_list',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='achieve_list', full_name='s2c_achieve_list.achieve_list', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=130,
  serialized_end=187,
)


_C2S_GET_ACHIEVE_REWARD = descriptor.Descriptor(
  name='c2s_get_achieve_reward',
  full_name='c2s_get_achieve_reward',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='achieveID', full_name='c2s_get_achieve_reward.achieveID', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=189,
  serialized_end=232,
)


_S2C_GET_ACHIEVE_REWARD = descriptor.Descriptor(
  name='s2c_get_achieve_reward',
  full_name='s2c_get_achieve_reward',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='code', full_name='s2c_get_achieve_reward.code', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=True, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=234,
  serialized_end=285,
)


_S2C_UPDATE_ACHIEVE = descriptor.Descriptor(
  name='s2c_update_achieve',
  full_name='s2c_update_achieve',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='achieve', full_name='s2c_update_achieve.achieve', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=287,
  serialized_end=341,
)

_S2C_ACHIEVE_LIST.fields_by_name['achieve_list'].message_type = _P_ACHIEVE_INFO
_S2C_GET_ACHIEVE_REWARD.fields_by_name['code'].enum_type = error_code_pb2._E_CODE
_S2C_UPDATE_ACHIEVE.fields_by_name['achieve'].message_type = _P_ACHIEVE_INFO
DESCRIPTOR.message_types_by_name['p_achieve_info'] = _P_ACHIEVE_INFO
DESCRIPTOR.message_types_by_name['c2s_achieve_list'] = _C2S_ACHIEVE_LIST
DESCRIPTOR.message_types_by_name['s2c_achieve_list'] = _S2C_ACHIEVE_LIST
DESCRIPTOR.message_types_by_name['c2s_get_achieve_reward'] = _C2S_GET_ACHIEVE_REWARD
DESCRIPTOR.message_types_by_name['s2c_get_achieve_reward'] = _S2C_GET_ACHIEVE_REWARD
DESCRIPTOR.message_types_by_name['s2c_update_achieve'] = _S2C_UPDATE_ACHIEVE

class p_achieve_info(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _P_ACHIEVE_INFO
  
  # @@protoc_insertion_point(class_scope:p_achieve_info)

class c2s_achieve_list(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _C2S_ACHIEVE_LIST
  
  # @@protoc_insertion_point(class_scope:c2s_achieve_list)

class s2c_achieve_list(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _S2C_ACHIEVE_LIST
  
  # @@protoc_insertion_point(class_scope:s2c_achieve_list)

class c2s_get_achieve_reward(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _C2S_GET_ACHIEVE_REWARD
  
  # @@protoc_insertion_point(class_scope:c2s_get_achieve_reward)

class s2c_get_achieve_reward(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _S2C_GET_ACHIEVE_REWARD
  
  # @@protoc_insertion_point(class_scope:s2c_get_achieve_reward)

class s2c_update_achieve(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _S2C_UPDATE_ACHIEVE
  
  # @@protoc_insertion_point(class_scope:s2c_update_achieve)

# @@protoc_insertion_point(module_scope)
