# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


import error_code_pb2
import common_pb2

DESCRIPTOR = descriptor.FileDescriptor(
  name='pet.proto',
  package='',
  serialized_pb='\n\tpet.proto\x1a\x10\x65rror_code.proto\x1a\x0c\x63ommon.proto\"\x12\n\x10\x63\x32s_get_pet_list\",\n\x10s2c_get_pet_list\x12\x18\n\x08pet_list\x18\x01 \x03(\x0b\x32\x06.p_pet\"\x1c\n\x0e\x63\x32s_pet_switch\x12\n\n\x02id\x18\x01 \x02(\x03\"+\n\x0es2c_pet_switch\x12\x19\n\x04\x63ode\x18\x01 \x01(\x0e\x32\x07.e_code:\x02ok\"1\n\rc2s_pet_up_lv\x12\n\n\x02id\x18\x01 \x02(\x03\x12\x14\n\x0c\x63ost_id_list\x18\x02 \x03(\x05\"*\n\rs2c_pet_up_lv\x12\x19\n\x04\x63ode\x18\x01 \x01(\x0e\x32\x07.e_code:\x02ok\".\n\x12s2c_add_pet_notice\x12\x18\n\x08pet_info\x18\x01 \x02(\x0b\x32\x06.p_pet\"B\n\x15s2c_update_pet_lv_exp\x12\n\n\x02id\x18\x01 \x02(\x03\x12\r\n\x02lv\x18\x02 \x01(\x05:\x01\x31\x12\x0e\n\x03\x65xp\x18\x03 \x01(\x05:\x01\x30')




_C2S_GET_PET_LIST = descriptor.Descriptor(
  name='c2s_get_pet_list',
  full_name='c2s_get_pet_list',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=45,
  serialized_end=63,
)


_S2C_GET_PET_LIST = descriptor.Descriptor(
  name='s2c_get_pet_list',
  full_name='s2c_get_pet_list',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='pet_list', full_name='s2c_get_pet_list.pet_list', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=65,
  serialized_end=109,
)


_C2S_PET_SWITCH = descriptor.Descriptor(
  name='c2s_pet_switch',
  full_name='c2s_pet_switch',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='id', full_name='c2s_pet_switch.id', index=0,
      number=1, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=111,
  serialized_end=139,
)


_S2C_PET_SWITCH = descriptor.Descriptor(
  name='s2c_pet_switch',
  full_name='s2c_pet_switch',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='code', full_name='s2c_pet_switch.code', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=True, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=141,
  serialized_end=184,
)


_C2S_PET_UP_LV = descriptor.Descriptor(
  name='c2s_pet_up_lv',
  full_name='c2s_pet_up_lv',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='id', full_name='c2s_pet_up_lv.id', index=0,
      number=1, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='cost_id_list', full_name='c2s_pet_up_lv.cost_id_list', index=1,
      number=2, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=186,
  serialized_end=235,
)


_S2C_PET_UP_LV = descriptor.Descriptor(
  name='s2c_pet_up_lv',
  full_name='s2c_pet_up_lv',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='code', full_name='s2c_pet_up_lv.code', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=True, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=237,
  serialized_end=279,
)


_S2C_ADD_PET_NOTICE = descriptor.Descriptor(
  name='s2c_add_pet_notice',
  full_name='s2c_add_pet_notice',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='pet_info', full_name='s2c_add_pet_notice.pet_info', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=281,
  serialized_end=327,
)


_S2C_UPDATE_PET_LV_EXP = descriptor.Descriptor(
  name='s2c_update_pet_lv_exp',
  full_name='s2c_update_pet_lv_exp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='id', full_name='s2c_update_pet_lv_exp.id', index=0,
      number=1, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='lv', full_name='s2c_update_pet_lv_exp.lv', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='exp', full_name='s2c_update_pet_lv_exp.exp', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=329,
  serialized_end=395,
)

_S2C_GET_PET_LIST.fields_by_name['pet_list'].message_type = common_pb2._P_PET
_S2C_PET_SWITCH.fields_by_name['code'].enum_type = error_code_pb2._E_CODE
_S2C_PET_UP_LV.fields_by_name['code'].enum_type = error_code_pb2._E_CODE
_S2C_ADD_PET_NOTICE.fields_by_name['pet_info'].message_type = common_pb2._P_PET
DESCRIPTOR.message_types_by_name['c2s_get_pet_list'] = _C2S_GET_PET_LIST
DESCRIPTOR.message_types_by_name['s2c_get_pet_list'] = _S2C_GET_PET_LIST
DESCRIPTOR.message_types_by_name['c2s_pet_switch'] = _C2S_PET_SWITCH
DESCRIPTOR.message_types_by_name['s2c_pet_switch'] = _S2C_PET_SWITCH
DESCRIPTOR.message_types_by_name['c2s_pet_up_lv'] = _C2S_PET_UP_LV
DESCRIPTOR.message_types_by_name['s2c_pet_up_lv'] = _S2C_PET_UP_LV
DESCRIPTOR.message_types_by_name['s2c_add_pet_notice'] = _S2C_ADD_PET_NOTICE
DESCRIPTOR.message_types_by_name['s2c_update_pet_lv_exp'] = _S2C_UPDATE_PET_LV_EXP

class c2s_get_pet_list(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _C2S_GET_PET_LIST
  
  # @@protoc_insertion_point(class_scope:c2s_get_pet_list)

class s2c_get_pet_list(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _S2C_GET_PET_LIST
  
  # @@protoc_insertion_point(class_scope:s2c_get_pet_list)

class c2s_pet_switch(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _C2S_PET_SWITCH
  
  # @@protoc_insertion_point(class_scope:c2s_pet_switch)

class s2c_pet_switch(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _S2C_PET_SWITCH
  
  # @@protoc_insertion_point(class_scope:s2c_pet_switch)

class c2s_pet_up_lv(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _C2S_PET_UP_LV
  
  # @@protoc_insertion_point(class_scope:c2s_pet_up_lv)

class s2c_pet_up_lv(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _S2C_PET_UP_LV
  
  # @@protoc_insertion_point(class_scope:s2c_pet_up_lv)

class s2c_add_pet_notice(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _S2C_ADD_PET_NOTICE
  
  # @@protoc_insertion_point(class_scope:s2c_add_pet_notice)

class s2c_update_pet_lv_exp(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _S2C_UPDATE_PET_LV_EXP
  
  # @@protoc_insertion_point(class_scope:s2c_update_pet_lv_exp)

# @@protoc_insertion_point(module_scope)
