# Generated by the protocol buffer compiler.  DO NOT EDIT!

from .rel.protobuf2 import descriptor
from .rel.protobuf2 import message
from .rel.protobuf2 import reflection
from .rel.protobuf2 import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='test.proto',
  package='',
  serialized_pb='\n\ntest.proto\"X\n\x08\x63\x32s_test\x12\x12\n\ntest_int64\x18\x01 \x01(\x03\x12\x12\n\ntest_int32\x18\x02 \x01(\x05\x12\x10\n\x08test_str\x18\x03 \x01(\t\x12\x12\n\ntest_float\x18\x04 \x01(\x02')




_C2S_TEST = descriptor.Descriptor(
  name='c2s_test',
  full_name='c2s_test',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='test_int64', full_name='c2s_test.test_int64', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='test_int32', full_name='c2s_test.test_int32', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='test_str', full_name='c2s_test.test_str', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='test_float', full_name='c2s_test.test_float', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=14,
  serialized_end=102,
)

DESCRIPTOR.message_types_by_name['c2s_test'] = _C2S_TEST

class c2s_test(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _C2S_TEST
  
  # @@protoc_insertion_point(class_scope:c2s_test)

# @@protoc_insertion_point(module_scope)
